export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const VISITOR_REGISTER_SUCCESS = "VISITOR_REGISTER_SUCCESS";
export const VISITOR_UPDATION_SUCCESS = "VISITOR_UPDATION_SUCCESS";
